[package]
name = "linear_dynamics"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.4.0"
nalgebra = "0.29"
uuid = "0.8"
formflight = { path = "../../formflight" }
